/* Fun facts the owl tells on the home page. Keep each one short, true and easy to read aloud. */
window.TRIVIA = [
  `An octopus has three hearts.`,
  `A group of flamingos is called a flamboyance.`,
  `Butterflies taste with their feet.`,
  `Cows have best friends and get upset when they are apart.`,
  `Elephants cannot jump.`,
  `Sea otters sometimes hold hands while they sleep, so they do not float apart.`,
  `A blue whale is the biggest animal that has ever lived.`,
  `A giraffe has the same number of neck bones as you: seven.`,
  `A cheetah can run about 100 kilometres per hour for a short time.`,
  `Some penguins give their mate a pebble as a gift.`,
  `Bees dance to tell their friends where the flowers are.`,
  `A hummingbird can fly backwards.`,
  `An ant can carry something much heavier than itself.`,
  `A crocodile cannot stick out its tongue.`,
  `I am an owl, and I can turn my head almost all the way round.`,
  `A kangaroo cannot walk backwards.`,
  `Dolphins sleep with half of their brain awake.`,
  `A newborn kangaroo is about as small as a jellybean.`,
  `A sloth can hold its breath for longer than a dolphin.`,
  `Frogs can drink water through their skin.`,
  `A starfish has no brain.`,
  `A koala can sleep for up to 20 hours a day.`,
  `An elephant's trunk has tens of thousands of tiny muscles.`,
  `Honey can last for thousands of years without going bad.`,
  `Seahorse dads carry the eggs, and they give birth to the babies.`,
  `Bats are the only mammals that can really fly.`,
  `A polar bear's skin is black under its white fur.`,
  `A day on Venus is longer than a year on Venus.`,
  `The Sun is a star. It just looks big because it is close.`,
  `More than a million Earths could fit inside the Sun.`,
  `Jupiter has a giant storm called the Great Red Spot. It is bigger than Earth.`,
  `Saturn is so light for its size that it would float in a giant bathtub.`,
  `The Moon is moving away from Earth by about 4 centimetres every year.`,
  `Footprints on the Moon can last for a very long time, because there is no wind.`,
  `Sunlight takes about 8 minutes to reach Earth.`,
  `A year on Mercury is only 88 Earth days long.`,
  `Your heart beats about 100,000 times every day.`,
  `Babies have more bones than grown-ups. Grown-ups have 206.`,
  `You blink about 15 times every minute.`,
  `Nobody else has the same fingerprints as you, not even a twin.`,
  `The smallest bone in your body is inside your ear.`,
  `Your tongue has thousands of tiny taste buds.`,
  `You are a tiny bit taller when you wake up than at bedtime.`,
  `Zero is an even number.`,
  `A googol is a 1 with one hundred zeros after it.`,
  `A baker's dozen is 13, one more than a dozen.`,
  `The little cells in a honeycomb are hexagons. That is a shape with 6 sides.`,
  `If you add up all the numbers on a clock face, 1 to 12, you get 78.`,
  `Start with 1 cent and double it every day. On day 30 you would have more than 5 million dollars.`,
  `Rhythm is a long word with no a, e, i, o or u in it.`,
  `The word queue is just the letter Q followed by four silent letters.`,
  `Bookkeeper has three double letters in a row: oo, kk and ee.`,
  `The letter E is the letter we use most in English.`,
  `The word alphabet comes from the first two Greek letters: alpha and beta.`,
  `Singapore is one big island and more than 60 little ones.`,
  `The Merlion has the head of a lion and the body of a fish.`,
  `Singapura means Lion City.`,
  `Singapore has four official languages: English, Malay, Mandarin and Tamil.`,
  `Changi Airport has a huge indoor waterfall.`,
  `The Singapore Botanic Gardens is a UNESCO World Heritage Site.`,
  `Singapore's national flower is a purple orchid called Vanda Miss Joaquim.`,
  `A rainbow is really a full circle. From the ground we usually see only half.`,
  `Lightning is hotter than the surface of the Sun.`,
  `The tallest trees in the world are taller than 100 metres.`,
  `Water covers about 70 out of every 100 parts of the Earth's surface.`,
  `Some bamboo can grow almost a metre in one day.`,
  `A big fluffy cloud can weigh as much as a hundred elephants.`,
  `Ice floats because it is lighter than water.`,
  `Popcorn pops because the tiny drop of water inside turns to steam.`
];
